### ISSUE TITLE
Add background and font colors

### ISSUE THREAD

**Issue by SJoWie80** [felixhahnweilheim/humhub-flex-theme#24]
Really love your work.!!
Any plans in adding background and font colors?

Thanks,
Joey

**Comment by felixhahnweilheim** [comment]
Hi, thanks a lot!
This is planned as the next step, but I can’t promise a date.

**Comment by felixhahnweilheim** [comment]
- [x] text colors (https://github.com/felixhahnweilheim/humhub-flex-theme/pull/27)
- [ ] background colors

**Comment by felixhahnweilheim** [comment]
Now text and background colors are implemented and it's time for testing.

(Unfortunately, some of the colors in HumHub are hard-coded (especially some white backgrounds). The Flex Theme only changes the colors that are implemented as a LESS variable. I will look into this in more detail at a later point.)

**Comment by felixhahnweilheim** [comment]
I'll close the issue. For light themes it works fine. (I am working on adding a dark mode in the develop branch. But there is the problem with hard coded colors.)

**Comment by felixhahnweilheim** [comment]
I'll close the issue. For light themes it works fine. (I am working on adding a dark mode in the develop branch. But there is the problem with hard coded colors.)
